### ISSUE TITLE
Connect error message does not report which line in model caused error

### ISSUE THREAD

**Issue by cbatten** [cornell-brg/pymtl#118]
PyMTL throws a ConnectError when there is a bitwidth mismatch between two ports being connected together, but it does not say what line in the model caused the error. This seems like a pretty big issue?

**Comment by dmlockhart** [comment]
Do you have a suggestion on how to fix this?

I don't think there's any way for the ConnectError exception to know what line the error occurred on, this information is only known further up the stack trace.  The stack trace does indeed report this information, the real complaint is that the stack trace is too long and the relevant information requires scrolling up.

The only way I can think to reduce the stack trace is to catch the ConnectError in a try/except block and keep reraising it until it reaches  s.connect or s.connect_dict... this seems really unclean.

**Comment by dmlockhart** [comment]
Actually, I think I might have a good way to do this... I didn't realize I could just catch the Exception using try/except within s.connect
