### ISSUE TITLE
Use apt-get install flex-old instead of flex

### ISSUE THREAD

**Issue by wizard97** [cornell-brg/pymtl#168]
Verilator fails to compile with only the "flex" package due to a missing `FileLexer.h`. You can see this header is no longer part of the flex package (https://packages.ubuntu.com/bionic/amd64/flex/filelist).

Instead the README should be updated to use flex-old, which has this header (https://packages.ubuntu.com/bionic/amd64/flex-old/filelist).

**Comment by cbatten** [comment]
great! thanks for the feedback. We are working on a new version of PyMTL which will use the latest version of Verilator too ...

**Comment by cbatten** [comment]
README updated!

**Comment by cbatten** [comment]
Thanks! So do we need to replace this:

```
 % sudo apt-get install git make autoconf g++ flex bison
```

with this:

```
% sudo apt-get install git make autoconf g++ libfl-dev bison
```

**Comment by wizard97** [comment]
Yep, that worked for me with the latest verilator!

**Comment by cbatten** [comment]
Thanks!
