### ISSUE TITLE
Cannot infer temporary bitwidth when a previously inferred temporary on RHS

### ISSUE THREAD

**Issue by dmlockhart** [cornell-brg/pymtl#44]
PyMTL allows the creation of temporaries in a number of scenarios when the right-hand-side (RHS) of an assignment allows for easy bitwidth inference:
```
  some_temp = s.port_a and s.port_b
  s.out.value = some_temp
```

However, if the RHS of a temporary assignment contains another temporary, this fails:
```
  some_temp = s.port_a and s.port_b
  some_temp2 = some_temp and s.port_c  # FAILS due to some_temp on RHS
```

**Comment by cbatten** [comment]
Awesome!
